In [1]:
!pip install importnb

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,confusion_matrix
from importnb import Notebook
import sys
sys.path.append("/content/drive/MyDrive/Colab Notebooks/portfolio/Linear Regression")
with Notebook():
  from Smiple_Linear_Regression import MyLinearRegression

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [29]:
class Mylogisticregression(MyLinearRegression):
  def __init__(self,X,y):
    self.X = X
    self.y = y

  def accuracy(self):
    acc_score =  accuracy_score(self.y_test,self.y_predict)
    print("This is acc_score : " ,acc_score)
    pre_score = precision_score(self.y_test,self.y_predict)
    print("This is pre_score : ",pre_score)
    rec_score = recall_score(self.y_test,self.y_predict)
    print("This is recall_score : ",rec_score)
    F1_score = f1_score(self.y_test,self.y_predict)
    print("This is f1_score : ",F1_score)
    con_matrix = confusion_matrix(self.y_test,self.y_predict)
    print("This is confusion_matrix : \n",con_matrix,"\n[[TN, FP]\n[FN, TP]]")

  def tradeoff(self,threadshold):
    y_probs = self.model.predict_proba(self.X_test)[:, 1]
    self.y_predict = (y_probs >= threadshold).astype(int)


def Readata():
  path = str(input("Enter your file path : "))
  df = pd.read_csv(path)
  X = df.iloc[:,:2]
  y = df.iloc[:,2]
  return X,y

X,y = Readata()

Enter your file path : /content/drive/MyDrive/Colab Notebooks/portfolio/Logistic Regression/student_exam_data.csv


In [37]:
forlogististic = Mylogisticregression(X,y)
forlogististic.data_split()
forlogististic.logisticfitmodel()
forlogististic.predict()
forlogististic.accuracy()
print("\n\n\n This is after trade off ")
forlogististic.tradeoff(0.89)
forlogististic.accuracy()

Mean Square Error is : 0.14
This is acc_score :  0.86
This is pre_score :  0.8235294117647058
This is recall_score :  0.7777777777777778
This is f1_score :  0.8
This is confusion_matrix : 
 [[58  6]
 [ 8 28]] 
[[TN, FP]
[FN, TP]]



 This is after trade off 
This is acc_score :  0.81
This is pre_score :  0.9473684210526315
This is recall_score :  0.5
This is f1_score :  0.6545454545454545
This is confusion_matrix : 
 [[63  1]
 [18 18]] 
[[TN, FP]
[FN, TP]]


In [6]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [8]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/portfolio/Logistic Regression/student_exam_data.csv")

In [9]:
df.columns

Index(['Study_Hours', 'Previous_Exam_Score', 'Pass/Fail'], dtype='object')

In [10]:
X =np.array(df[["Study_Hours","Previous_Exam_Score"]])
y = np.array(df["Pass/Fail"])
X = np.hstack((X,np.ones((len(X),1))))

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)
X_test.shape

(100, 3)

In [12]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 3)
(100, 3)
(400, 1)
(100, 1)


In [13]:
def sigmoid(z):
  return 1/(1+np.exp(-z))
def hypothesis(X,w):
  # X = 320,3
  # w = 3 , 1
  h = X @ w
  z = sigmoid(h)
  return z

def cost_function(X,y,w):
  m = len(y)
  predi = hypothesis(X,w)
  error = (-1/m)*np.sum(y*np.log(predi)+(1-y)*np.log(1-predi))
  return error

In [14]:
def gradient_descent(X,y,alpha,iter_num):
  m, n = X.shape
  w = np.ones((n, 1))
  J_his = []
  # X = 320 x 3
  # y = 320 x 1
  # w = 3 x 1
  for i in range(iter_num):
    predict = hypothesis(X,w)
    gradient = (1/m)*(X.T @ (predict-y))
    J_his.append(cost_function(X_train,y_train,w))
    w = w - alpha*gradient

  return J_his,w

J_his,w = gradient_descent(X_train,y_train,0.001,700000)
J_his[699990:]

#0.6839402255654358
#0.408410538205188
#0.2839628145287589
#0.27279721490691344

<ipython-input-13-63ade0cd5aa0>:13: RuntimeWarning: divide by zero encountered in log
  error = (-1/m)*np.sum(y*np.log(predi)+(1-y)*np.log(1-predi))
<ipython-input-13-63ade0cd5aa0>:13: RuntimeWarning: invalid value encountered in multiply
  error = (-1/m)*np.sum(y*np.log(predi)+(1-y)*np.log(1-predi))


[np.float64(0.2727975690838464),
 np.float64(0.27279752973037463),
 np.float64(0.27279749037702267),
 np.float64(0.27279745102379044),
 np.float64(0.2727974116706781),
 np.float64(0.2727973723176855),
 np.float64(0.27279733296481273),
 np.float64(0.27279729361205984),
 np.float64(0.27279725425942675),
 np.float64(0.27279721490691344)]

In [15]:
def hypothesiss(X,w):
  # X = 320,3
  # w = 3 , 1
  h = X @ w
  print(X.shape)
  print(w.shape)
  print(h.shape)
  z = sigmoid(h)

  return z
def predict(X, w, threshold=0.55):
    # Compute probabilities
    probs = hypothesis(X, w)
    # Convert to binary predictions
    return (probs >= threshold).astype(int)
y_pred = predict(X_test, w)
y_pred.shape

(100, 1)

In [16]:
def accuracy(y, y_pred):
 # Ensure proper shape
    correct = np.sum(y == y_pred)
    total = len(y)
    acc = (correct / total) * 100
    print(correct)
    print(len(y_pred))
    print(total)
    print(acc)
    return acc







acc = accuracy(y_test, y_pred)

87
100
100
87.0


In [17]:
w
#array([[  0.81445648],
#      [  0.09809428],
 #     [-12.41575859]])

array([[  0.81445648],
       [  0.09809428],
       [-12.41575859]])

In [18]:
print(f"Accuracy: {acc:.2f}%")

Accuracy: 87.00%


In [19]:
print("Comparison result:", y_train == y_pred)


ValueError: operands could not be broadcast together with shapes (400,1) (100,1) 

In [ ]:
y_train.shape

In [ ]:
X_class_0 = X[y == 0]
X_class_1 = X[y == 1]

# Plot
plt.scatter(X_class_0[:, 0], X_class_0[:, 1], color='blue', label='Class 0')
plt.scatter(X_class_1[:, 0], X_class_1[:, 1], color='red', label='Class 1')

# Add labels and title
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.title('Scatter Plot of Two Features with Binary Labels')
plt.legend()
plt.show()

In [ ]:
# Create and train the model
from sklearn.datasets import make_classification

X =df[["Study_Hours","Previous_Exam_Score"]]
y =df["Pass/Fail"]
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)
# Predict on the test data
y_pred = model.predict(X_test)
# Accuracy
def accuracy(y, y_pred):
 # Ensure proper shape
    correct = np.sum(y == y_pred)
    total = len(y)
    acc = (correct / total) * 100
    print(correct)
    print(len(y_pred))
    print(total)
    print(acc)
    return acc
acc = accuracy(y_test, y_pred)