In [1]:
from google.colab import drive
drive.flush_and_unmount()


Drive not mounted, so nothing to flush and unmount.


In [3]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import Normalizer,MinMaxScaler
from tensorflow.keras.layers import Input,Dense
from tensorflow.keras import Sequential
from tensorflow.keras.activations import linear
from tensorflow.keras.optimizers import Adam



In [5]:
import torch
torch.cuda.is_available()


True

In [6]:
df_userweight = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/portfolio/recommandation/content_base/content_base/userweight.csv")
rating_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/portfolio/recommandation/content_base/content_base/ratings.csv")
movie_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/portfolio/recommandation/content_base/content_base/movies_file.csv")
movie_weight_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/portfolio/recommandation/content_base/content_base/mydata.csv")

In [7]:
59047 +3376
len(movie_df["movieId"].unique())

62423

In [8]:
movie_df[~movie_df["movieId"].isin(rating_df["movieId"].unique())]["movieId"]


8371      25817
8763      26361
11556     52696
11997     56513
12173     58209
          ...  
62238    208411
62239    208413
62240    208415
62298    208655
62342    208804
Name: movieId, Length: 3376, dtype: int64

In [9]:
list_rate_movie = np.sort(rating_df["movieId"].unique())
list_rate_movie[:62420]

array([     1,      2,      3, ..., 209163, 209169, 209171])

In [ ]:
# list_rate_movie = np.sort(rating_df["movieId"].unique())
# column = ['movieId','Adventure', 'Comedy', 'Action', 'Drama', 'Crime', 'Children', 'Mystery', 'Documentary', 'Animation', 'Thriller', 'Horror', 'Fantasy', 'Western', 'Film-Noir', 'Romance', 'War', 'Sci-Fi', 'Musical', 'IMAX']
# final_movie_weight = pd.DataFrame(columns = column)
for i in list_rate_movie[1:100]:
  rated_user_list = rating_df[rating_df["movieId"] == i]["userId"]
  user_rated_list = rating_df[rating_df["movieId"] == i]["rating"]
  weight_of_user = df_userweight[df_userweight["UserId"].isin(rated_user_list)]
  X = np.array(weight_of_user.iloc[:,1:], dtype=np.float32)
  y = np.array(user_rated_list , dtype=np.float32)
  model = Sequential([
    Input (shape = (19,)),
    Dense (units = 1)])
  model.compile(optimizer = "adam",loss = "mean_squared_error")
  model.fit(X,y,epochs=20,verbose=0.2)
  scaler = MinMaxScaler()
  minmaxscaler = scaler.fit_transform(model.get_weights()[0])
  # print(minmaxscaler)
  moviee_weight = minmaxscaler.reshape(-1,19)
  # print(moviee_weight)
  normalizer = Normalizer(norm = 'l1')
  final_weight = normalizer.transform(moviee_weight)
  # print(final_weight)
  # print(type(final_weight))
  final_weight = np.vstack((i,final_weight.reshape(19,-1))).flatten()
  movie_weight_df.loc[len(movie_weight_df)] = final_weight
  print(f"                  {i}                          ")
movie_weight_df.to_csv('my_data.csv', index=False)



Epoch 1/20
Epoch 2/20
Epoch 3/20
Epoch 4/20
Epoch 5/20
Epoch 6/20
Epoch 7/20
Epoch 8/20
Epoch 9/20
Epoch 10/20
Epoch 11/20
Epoch 12/20
Epoch 13/20
Epoch 14/20
Epoch 15/20
Epoch 16/20
Epoch 17/20
Epoch 18/20
Epoch 19/20
Epoch 20/20
                  2                          
Epoch 1/20
Epoch 2/20
Epoch 3/20
Epoch 4/20
Epoch 5/20
Epoch 6/20
Epoch 7/20
Epoch 8/20
Epoch 9/20
Epoch 10/20
Epoch 11/20
Epoch 12/20
Epoch 13/20
Epoch 14/20
Epoch 15/20
Epoch 16/20
Epoch 17/20
Epoch 18/20
Epoch 19/20
Epoch 20/20
                  3                          
Epoch 1/20
Epoch 2/20
Epoch 3/20
Epoch 4/20
Epoch 5/20
Epoch 6/20
Epoch 7/20
Epoch 8/20
Epoch 9/20
Epoch 10/20
Epoch 11/20
Epoch 12/20
Epoch 13/20
Epoch 14/20
Epoch 15/20
Epoch 16/20
Epoch 17/20
Epoch 18/20
Epoch 19/20
Epoch 20/20
                  4                          
Epoch 1/20
Epoch 2/20
Epoch 3/20
Epoch 4/20
Epoch 5/20
Epoch 6/20
Epoch 7/20
Epoch 8/20
Epoch 9/20
Epoch 10/20
Epoch 11/20
Epoch 12/20
Epoch 13/20
Epoch 14/20
Epoch 15/2

In [ ]:
model = Sequential([
    Input (shape = (19,)),
    Dense (units = 1)
])

In [ ]:
X

array([[0.1541294 , 0.10994214, 0.12835349, ..., 0.05917938, 0.0189374 ,
        0.01499211],
       [0.09825151, 0.08177539, 0.16355078, ..., 0.11136516, 0.00289173,
        0.04068594],
       [0.1376399 , 0.11486354, 0.18142548, ..., 0.10563519, 0.01001374,
        0.03907324],
       ...,
       [0.09542137, 0.12103517, 0.11652289, ..., 0.05202389, 0.02043796,
        0.01725282],
       [0.09660204, 0.10923546, 0.11326508, ..., 0.0922457 , 0.00479198,
        0.02352429],
       [0.06177326, 0.17005815, 0.05741279, ..., 0.03197674, 0.01235465,
        0.0181686 ]], dtype=float32)

In [ ]:
model.compile(optimizer = "adam",loss = "mean_squared_error")

In [ ]:
model.fit(X,y,epochs=50,verbose=1)

Epoch 1/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.8071
Epoch 2/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.7996
Epoch 3/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.8077
Epoch 4/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.7967
Epoch 5/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.7978
Epoch 6/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.8037
Epoch 7/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.8101
Epoch 8/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.8069
Epoch 9/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.8094
Epoch 10/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.7979
Epoch 11/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.8068
Epoch 12/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.7935
Epoch 13/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.8118
Epoch 14/50
1791/1791 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.8059
Epoch 15/50
1791/1791 ━━━━━━━

In [ ]:
model.get_weights()[0]

array([[ 2.7155035 ],
       [ 3.0092652 ],
       [ 1.0108685 ],
       [ 1.1168929 ],
       [ 1.4944518 ],
       [ 6.8696537 ],
       [-0.5767172 ],
       [-1.6185262 ],
       [ 4.834845  ],
       [ 2.7452185 ],
       [ 0.11536909],
       [-0.87224984],
       [ 8.074911  ],
       [ 9.4704275 ],
       [ 0.3904749 ],
       [ 1.797796  ],
       [ 1.1681563 ],
       [ 0.09776808],
       [ 0.837167  ]], dtype=float32)

In [ ]:

scaler = MinMaxScaler()
minmaxscaler = scaler.fit_transform(model.get_weights()[0])
print(minmaxscaler)
moviee_weight = minmaxscaler.reshape(-1,19)
print(moviee_weight)
normalizer = Normalizer(norm = 'l1')
final_weight = normalizer.transform(moviee_weight)
print(final_weight)
print(type(final_weight))
userID = np.array([1])
final_weight = np.vstack((1,final_weight.reshape(19,-1))).flatten()
final_weight
# moviee_weight = final_weight.reshape(-1,20).flatten()
# moviee_weight
# moviee_weight = np.vstack((1,np.array([final_weight])))
# moviee_weight = final_weight.reshape(-1,20).flatten()
# moviee_weight.shape
# MinMaxScaler.fit_transform(moviee_weight)

[[0.39084208]
 [0.41733345]
 [0.23711838]
 [0.24667963]
 [0.28072783]
 [0.76546264]
 [0.09395017]
 [0.        ]
 [0.5819639 ]
 [0.3935218 ]
 [0.15636238]
 [0.06729908]
 [0.87415254]
 [1.        ]
 [0.18117139]
 [0.30808336]
 [0.25130254]
 [0.15477513]
 [0.221454  ]]
[[0.39084208 0.41733345 0.23711838 0.24667963 0.28072783 0.76546264
  0.09395017 0.         0.5819639  0.3935218  0.15636238 0.06729908
  0.87415254 1.         0.18117139 0.30808336 0.25130254 0.15477513
  0.221454  ]]
[[0.05901997 0.06302036 0.03580658 0.0372504  0.04239192 0.11559036
  0.01418715 0.         0.08788074 0.05942462 0.02361185 0.01016265
  0.13200332 0.15100719 0.02735818 0.0465228  0.03794849 0.02337216
  0.03344114]]
<class 'numpy.ndarray'>


array([1.        , 0.05901997, 0.06302036, 0.03580658, 0.0372504 ,
       0.04239192, 0.11559036, 0.01418715, 0.        , 0.08788074,
       0.05942462, 0.02361185, 0.01016265, 0.13200332, 0.15100719,
       0.02735818, 0.0465228 , 0.03794849, 0.02337216, 0.03344114])

In [ ]:
column = ['movieId','Adventure', 'Comedy', 'Action', 'Drama', 'Crime', 'Children', 'Mystery', 'Documentary', 'Animation', 'Thriller', 'Horror', 'Fantasy', 'Western', 'Film-Noir', 'Romance', 'War', 'Sci-Fi', 'Musical', 'IMAX']
final_movie_weight = pd.DataFrame(columns = column)
final_movie_weight.loc[len(final_movie_weight)] = final_weight
final_movie_weight

movieId  Adventure   Comedy    Action    Drama     Crime  Children  \
0      1.0    0.05902  0.06302  0.035807  0.03725  0.042392   0.11559   

    Mystery  Documentary  Animation  Thriller    Horror   Fantasy   Western  \
0  0.014187          0.0   0.087881  0.059425  0.023612  0.010163  0.132003   

   Film-Noir   Romance       War    Sci-Fi   Musical      IMAX  
0   0.151007  0.027358  0.046523  0.037948  0.023372  0.033441

In [ ]:
moviee_weight = model.weights()[0]
moviee_weight

TypeError: 'list' object is not callable

In [ ]:
MinMaxScaler.fit()

Index(['movieId', 'title', 'genres', 'Adventure', 'Comedy', 'Action', 'Drama',
       'Crime', 'Children', 'Mystery', 'Documentary', 'Animation', 'Thriller',
       'Horror', 'Fantasy', 'Western', 'Film-Noir', 'Romance', 'War', 'Sci-Fi',
       'Musical', 'IMAX'],
      dtype='object')

In [ ]:
df_userweight.columns

Index(['UserId', 'Adventure', 'Comedy', 'Action', 'Drama', 'Crime', 'Children',
       'Mystery', 'Documentary', 'Animation', 'Thriller', 'Horror', 'Fantasy',
       'Western', 'Film-Noir', 'Romance', 'War', 'Sci-Fi', 'Musical', 'IMAX'],
      dtype='object')

In [ ]:
59047 + 3376

62423